Repository unb-mds/2024-1-MinasDeCultura, pull requests merged in 2024-07, with the labels that each got.

#55 Criação do ambiente de desenvolvimento
  backend/dockerfile
  backend/requirements.txt
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__init__.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/__init__.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/settings.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/items.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/middlewares.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/pipelines.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/resultado.json
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/settings.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__init__.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/__init__.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/juiz_de_fora_spider.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/prototipo_spider.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/prototipo_spider.py
  backend/webscrapy/minas_de_cultura_scrapy/resultado.json
  backend/webscrapy/minas_de_cultura_scrapy/scrapy.cfg
  docker-compose.yml
Labels: feature

#60 Raspador carrossel
  .gitignore
  backend/raspador.py
Labels: medium priority, feature

#67 Desenvolvimento da Responsividade, Menu de Navegação e Aperfeiçoamento do Código
  front/src/app/Sobre/page.tsx
  front/src/app/page.tsx
  front/src/assets/logo_vermelha.png
  front/src/components/Filtro.tsx
  front/src/components/Footer.tsx
  front/src/components/Header.tsx
  front/tailwind.config.ts
Labels: medium priority, feature

#68 Responsividade components
  front/src/app/page.tsx
  front/src/components/Busca.tsx
  front/src/components/Footer.tsx
  front/src/components/Grafico.tsx
Labels: medium priority

#69 Criação do raspador da cidade de juiz de fora (REFEITO)
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/juiz_de_fora.py
  docs/Como executar/Tutorial_scrapy.md
Labels: high priority, feature
