Repository unb-mds/2024-1-MinasDeCultura, pull requests merged in 2024-08, with the labels that each got.

#75 Melhorias na Responsividade e Layout das Páginas Home e Sobre
  docker-compose.yml
  front.Dockerfile
  front/src/app/Sobre/page.tsx
  front/src/app/page.tsx
  front/src/assets/logo_vermelha.png
  front/src/components/Busca.tsx
  front/src/components/Filtro.tsx
  front/src/components/Footer.tsx
  front/src/components/Grafico.tsx
  front/src/components/Header.tsx
  front/tailwind.config.ts
Labels: medium priority, feature

#78 Implementação do Dockerfile, Docker Compose e Script de Inserção de Dados JSON no PostgreSQL (REFEITO)
  .gitignore
  backend/db-scripts/createTable.js
  backend/db-scripts/index.js
  backend/db-scripts/package-lock.json
  backend/db-scripts/package.json
  backend/webscrapy/minas_de_cultura_scrapy/resultado.json
  docker-compose.yml
Labels: high priority, feature

#80 Criação de API para Consulta de Dados de Licitações
  backend/api/app.js
  backend/api/db.js
  backend/db-scripts/package-lock.json
  backend/package-lock.json
  backend/package.json
Labels: high priority, feature

#79 Ajustando a build do projeto
  backend/dockerfile
  docker-compose.yml
  front/Dockerfile
Labels: medium priority, fix

#82 [PR] Implementação do Protótipo de API, Backend, Frontend e Responsividade Web
  .gitignore
  backend/api/app.js
  backend/api/db.js
  backend/db-scripts/createTable.js
  backend/db-scripts/index.js
  backend/dockerfile
  backend/package-lock.json
  backend/package.json
  backend/raspador.py
  backend/requirements.txt
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__init__.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/__init__.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/settings.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/items.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/middlewares.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/pipelines.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/resultado.json
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/settings.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__init__.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/__init__.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/juiz_de_fora_spider.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/prototipo_spider.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/juiz_de_fora.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/prototipo_spider.py
  backend/webscrapy/minas_de_cultura_scrapy/resultado.json
  backend/webscrapy/minas_de_cultura_scrapy/scrapy.cfg
  docker-compose.yml
  docs/Como executar/Tutorial_scrapy.md
  front/Dockerfile
  front/package-lock.json
  front/package.json
  front/src/app/Pesquisa/page.tsx
  front/src/app/Sobre/page.tsx
  front/src/app/layout.tsx
  front/src/app/page.tsx
  front/src/assets/imggit.png
  front/src/assets/logo_vermelha.png
  front/src/components/Busca.tsx
  front/src/components/Filtro.tsx
  front/src/components/Footer.tsx
  front/src/components/Grafico.tsx
  front/src/components/Header.tsx
  front/src/components/Slider.tsx
  front/tailwind.config.ts
  webscrapy/minas_de_cultura_scrapy/resultado.json
Labels: high priority, feature

#88 Implementação de Testes para Componentes do Front-End e Atualização da Documentação
  docs/Como executar/Front-end/Executar os Testes.md
  front/__mocks__/fileMock.js
  front/__mocks__/next/image.js
  front/babel.config.js
  front/jest.config.js
  front/jest.setup.js
  front/next.config.js
  front/package-lock.json
  front/package.json
  front/src/app/Sobre/page.tsx
  front/src/app/page.tsx
  front/src/components/Busca.tsx
  front/src/components/Header.tsx
  front/src/components/Informacoes.tsx
  front/src/components/Pilares.tsx
  front/src/testes/Busca.test.jsx
  front/src/testes/Filtro.test.jsx
  front/src/testes/Header.test.jsx
  front/src/testes/Informacoes.test.jsx
  front/src/testes/Pilares.test.jsx
  front/src/types/images.d.ts
Labels: medium priority, feature

#90 Implementação de Testes para Componentes do Front-End e correção do bug no slider.
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/juiz_de_fora.py
  docs/Como executar/Tutorial_scrapy.md
  front/jest.setup.js
  front/src/components/Footer.tsx
  front/src/components/Slider.tsx
  front/src/testes/Footer.test.jsx
  front/src/testes/Grafico.test.jsx
  front/src/testes/Slider.test.jsx
Labels: medium priority, feature

#96 Integracao slider
  .gitignore
  backend/raspador.py
  docker-compose.yml
  front/src/components/Slider.tsx
Labels: medium priority, feature

#89 Raspador montes claros
  backend/Montes_claros_selenium/despesas_montes_claros.json
  backend/Montes_claros_selenium/filtrar_csv.py
  backend/Montes_claros_selenium/montes_claros.py
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/resultado.json
  backend/webscrapy/minas_de_cultura_scrapy/resultado.json
  webscrapy/Montes_claros_selenium/despesas_montes_claros.json
  webscrapy/Montes_claros_selenium/filtrar_csv.py
  webscrapy/Montes_claros_selenium/montes_claros.py
Labels: medium priority, feature

#98 Integracao slider
  .gitignore
  docker-compose.yml
  front/src/components/Slider.tsx
Labels: medium priority, feature

#108 Implementação de Testes Unitários, Novos Componentes e Melhorias Gerais
  docs/Como executar/Front-end/Executar os Testes.md
  front/__mocks__/fileMock.js
  front/__mocks__/next/image.js
  front/__mocks__/styleMock.js
  front/babel.config.js
  front/jest.config.js
  front/jest.setup.js
  front/next.config.js
  front/package-lock.json
  front/package.json
  front/src/app/Sobre/page.tsx
  front/src/app/page.tsx
  front/src/components/Busca.tsx
  front/src/components/Filtro.tsx
  front/src/components/Footer.tsx
  front/src/components/Header.tsx
  front/src/components/Informacoes.tsx
  front/src/components/Pilares.tsx
  front/src/components/Slider.tsx
  front/src/testes/Busca.test.jsx
  front/src/testes/Filtro.test.jsx
  front/src/testes/Footer.test.jsx
  front/src/testes/Grafico.test.jsx
  front/src/testes/Header.test.jsx
  front/src/testes/Informacoes.test.jsx
  front/src/testes/Pilares.test.jsx
  front/src/testes/Slider.test.jsx
  front/src/types/images.d.ts
Labels: high priority, documentation, fix, feature

#112 Refatoração da API para lidar com o campo de 'cidade' do banco de dados
  backend/api/app.js
  backend/db-scripts/createTable.js
  backend/db-scripts/insertData.js
  backend/webscrapy/minas_de_cultura_scrapy/resultado.json
Labels: high priority, fix

#111 Automatizacao testes e ajustes na build
  .github/workflows/jest_tests.yml
  backend/dockerfile
  docker-compose.yml
  front/Dockerfile
Labels: high priority, feature

#113 Criação do componente Integrantes e alguns ajustes no frontend
  front/package-lock.json
  front/src/app/Sobre/page.tsx
  front/src/assets/unblogo.png
  front/src/components/Footer.tsx
  front/src/components/Header.tsx
  front/src/components/Informacoes.tsx
  front/src/components/Integrantes.tsx
  front/src/components/Pilares.tsx
  front/src/components/Slider.tsx
  front/src/testes/Informacoes.test.jsx
  front/src/testes/Integrantes.test.jsx
  front/src/testes/Slider.test.jsx
Labels: medium priority, fix

#115 Subindo mudanças de documentação da frontend para a developer
  docs/Como executar/Raspadores/Selenium.md
  docs/Como executar/Raspadores/Tutorial_scrapy.md
  docs/Como executar/passo-a-passo-back.md
  docs/Como executar/passo-a-passo-backend.md
  docs/Guia de estudos/Selenium.md
  docs/atas/ata-reuniao1.md
  docs/atas/ata-reuniao10.md
  docs/atas/ata-reuniao11.md
  docs/atas/ata-reuniao2.md
  docs/atas/ata-reuniao3.md
  docs/atas/ata-reuniao4.md
  docs/atas/ata-reuniao5.md
  docs/atas/ata-reuniao6.md
  docs/atas/ata-reuniao7.md
  docs/atas/ata-reuniao8.md
  docs/atas/ata-reuniao9.md
  docs/sprints/sprint0.md
  docs/sprints/sprint1.md
  docs/sprints/sprint2.md
  docs/sprints/sprint3.md
  docs/sprints/sprint4.md
  prototipo_form/.eslintrc.json
  prototipo_form/.gitignore
  prototipo_form/README.md
  prototipo_form/image.png
  prototipo_form/next.config.mjs
  prototipo_form/package-lock.json
  prototipo_form/package.json
  prototipo_form/postcss.config.mjs
  prototipo_form/src/app/favicon.ico
  prototipo_form/src/app/globals.css
  prototipo_form/src/app/layout.tsx
  prototipo_form/src/app/page.tsx
  prototipo_form/src/components/QueryForm.tsx
  prototipo_form/src/types.ts
  prototipo_form/tailwind.config.ts
  prototipo_form/tsconfig.json
Labels: low priority, documentation

#114 Ajuste juiz de fora
  .gitignore
  README.md
  backend/Montes_claros_selenium/despesas_montes_claros.json
  backend/Montes_claros_selenium/filtrar_csv.py
  backend/Montes_claros_selenium/montes_claros.py
  backend/webscrapy/minas_de_cultura_scrapy/despesas.json
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/__init__.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/__init__.cpython-312.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/settings.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/__pycache__/settings.cpython-312.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/resultado.json
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/__init__.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/__init__.cpython-312.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/juiz_de_fora.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/juiz_de_fora.cpython-312.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/prototipo_spider.cpython-310.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/__pycache__/prototipo_spider.cpython-312.pyc
  backend/webscrapy/minas_de_cultura_scrapy/minas_de_cultura_scrapy/spiders/juiz_de_fora.py
  backend/webscrapy/minas_de_cultura_scrapy/resultado.json
  docs/Como executar/Tutorial_selenium.md
  docs/index.md
Labels: high priority, improvement

#118 Requisição da API para o front-end
  backend/api/app.js
  backend/db-scripts/insertData.js
  backend/package-lock.json
  backend/package.json
  front/jest.config.js
  front/package-lock.json
  front/package.json
  front/src/components/Filtro.tsx
  front/src/services/api.ts
Labels: medium priority, improvement

#120 Implementação do menu de Acessibilidade, mudança de estilo dos componentes para modo dark e alto contraste.
  front/src/app/Pesquisa/page.tsx
  front/src/app/Sobre/page.tsx
  front/src/app/globals.css
  front/src/app/page.tsx
  front/src/components/Busca.tsx
  front/src/components/Filtro.tsx
  front/src/components/Grafico.tsx
  front/src/components/Header.tsx
  front/src/components/Informacoes.tsx
  front/src/components/Integrantes.tsx
  front/src/components/Pilares.tsx
  front/src/components/Slider.tsx
  front/tailwind.config.ts
Labels: high priority, feature

#123 Implementação da API de Consulta de licitações, cidades e unidades administrativas
  .gitignore
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/config/supabaseClient.js
  backend/src/controllers/citiesController.js
  backend/src/controllers/tendersController.js
  backend/src/controllers/unitsController.js
  backend/src/index.js
  backend/src/routes/citiesRoutes.js
  backend/src/routes/tendersRoutes.js
  backend/src/routes/unitsRoutes.js
  backend/src/scripts/insertData.js
  backend/src/scripts/insertInitialData.js
  backend/src/services/citiesService.js
  backend/src/services/tendersService.js
  backend/src/services/unitsService.js
  docs/Como executar/backend/Executar a API.md
Labels: high priority, documentation, fix, feature

#124 Raspador do portal da transparência de Minas Gerais, Json com dados de 20 anos
  backend/Selenium_transparencia/resultado.json
  backend/Selenium_transparencia/transparencia.py
Labels: medium priority

#130 Teste de integração do backend
  backend/__tests__/citiesAPI.spec.js
  backend/__tests__/supabaseClient.spec.js
  backend/__tests__/tendersAPI.spec.js
  backend/__tests__/unitsAPI.spec.js
  backend/api/app.js
  backend/api/db.js
  backend/db-scripts/createTable.js
  backend/db-scripts/insertData.js
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
Labels: medium priority, test

#129 Integração da API para Exibição de Gráficos na Guia Pesquisa
  docs/Como executar/Front-end/Testes unitários/Testes do Componente Filtro.md
  front/src/app/Sobre/page.tsx
  front/src/app/globals.css
  front/src/components/Filtro.tsx
  front/src/components/Header.tsx
  front/src/services/api.ts
  front/src/testes/Filtro.test.jsx
Labels: high priority, feature

#133 Implementação de Endpoints para Consulta de Licitações Anuais e Mensais
  backend/README.md
  backend/src/controllers/tendersMonthController.js
  backend/src/controllers/tendersYearController.js
  backend/src/index.js
  backend/src/routes/tendersMonthRoutes.js
  backend/src/routes/tendersYearRoutes.js
  backend/src/scripts/insertTendersMonth.js
  backend/src/scripts/insertTendersYear.js
  backend/src/services/tendersMonthService.js
  backend/src/services/tendersYearService.js
  docs/Como executar/backend/Executar a API.md
Labels: high priority, documentation, feature
